### ISSUE TITLE
Stop ajo spam

### ISSUE THREAD

**Issue by axl89** [ass-a-service/ajobot#28]
Right now in `v2.1.3` you can spam ajos as much as you want and you only get the vampire once in a while. The goal is to be able to stop this behavior so spamming ajos is not effective. Some ideas:

- Make the vampire more aggressive over time (suggested in #3)
- Implement some kind of _curse_ that the player get when spamming a lot and the curse reduces the effectiveness of the ajos. Let's say you say 100 ajos and you only get 90%, then the curse evolves and 50%, then it keeps evolving and only 25%, etc. so at the end the player stops and eventually the curse stops and the farming can be resumed.

**Comment by Zymna** [comment]
Closed with aggressive vampire.
