### ISSUE TITLE
Fix roulette

### ISSUE THREAD

**Issue by heyen** [ass-a-service/ajobot#50]
### Current Behavior

You calle roulette command and does nothing

### Expected Behavior

It should do the roulette thing

### Steps to Reproduce

Write /roulette
Submit
Wait

### Extra informatio that you want to share.

Roulette shot is working

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Zymna** [comment]
Fixed
