### ISSUE TITLE
New item: Caramelo

### ISSUE THREAD

**Issue by mmarinero** [ass-a-service/ajobot#54]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Item: Caramelo
Description: Given to another player and causes vampires to attacked the other player more frequently
Stacked: No
Traded: Yes
Emoji: 🍬 

### Describe the solution you'd like.

Implement Caramelo
I want to curse the people

**Comment by axl89** [comment]
This was implemented in v5.0.0. Closing the issue.
