### ISSUE TITLE
New item: Discombobulate amplifier

### ISSUE THREAD

**Issue by mmarinero** [ass-a-service/ajobot#55]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Item: Discombobulate amplifier
Description: Upgrades your discombobulate damage
Can be stacked: No
Can be traded: Yes
Chance to be obtained: 0.03%
Emoji: 🍆 

### Describe the solution you'd like.

New item to discombobulate those that wrong me

**Comment by Zymna** [comment]
Done
